# Generated by Django 6.1.1 on 2026-09-18 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lavozim'),
        ),
        migrations.CreateModel(
            name='DigitalKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Kalit ID')),
                ('purpose', models.CharField(choices=[('AUTHENTICATION', 'Tizimga kirish')], default='AUTHENTICATION', max_length=30, verbose_name='Maqsad')),
                ('algorithm', models.CharField(default='Ed25519', max_length=50, verbose_name='Algoritm')),
                ('public_key', models.TextField(verbose_name='Ochiq kalit')),
                ('fingerprint', models.CharField(max_length=128, unique=True, verbose_name='Fingerprint')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_keys', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'ERI kaliti',
                'verbose_name_plural': 'ERI kalitlari',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='one_active_key_per_user')],
            },
        ),
    ]
