# Generated by Django 6.1.1 on 2026-09-18 12:02

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_organization_user_position_digitalkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(default=accounts.models.generate_challenge, max_length=128, unique=True, verbose_name='Challenge')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('expires_at', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Ishlatilgan vaqt')),
                ('digital_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_challenges', to='accounts.digitalkey', verbose_name='ERI kaliti')),
            ],
            options={
                'verbose_name': 'Login Challenge',
                'verbose_name_plural': 'Login Challenges',
                'ordering': ['-created_at'],
            },
        ),
    ]
