# Generated by Django 6.1.1 on 2026-09-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalkey',
            name='purpose',
            field=models.CharField(choices=[('AUTHENTICATION', 'Tizimga kirish'), ('ENCRYPTION', 'Xatlarni shifrlash')], default='AUTHENTICATION', max_length=30, verbose_name='Maqsad'),
        ),
    ]
