# Generated by Django 6.1.1 on 2026-09-21 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Mavzu')),
                ('body', models.TextField(blank=True, verbose_name='Xabar matni')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('SENT', 'Yuborilgan')], default='DRAFT', max_length=10, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan vaqt')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqt')),
                ('forwarded_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='messaging.message', verbose_name='Forward qilingan xabar')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.message', verbose_name='Javob berilgan xabar')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='messaging.message', verbose_name='Xabar')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
            ],
            options={
                'verbose_name': 'Xabar qabul qiluvchisi',
                'verbose_name_plural': 'Xabar qabul qiluvchilari',
                'constraints': [models.UniqueConstraint(fields=('message', 'recipient'), name='unique_message_recipient')],
            },
        ),
        migrations.CreateModel(
            name='MessageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='O‘qilgan')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='O‘qilgan vaqt')),
                ('is_starred', models.BooleanField(default=False, verbose_name='Belgilangan')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arxivlangan')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='O‘chirilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='messaging.message', verbose_name='Xabar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_states', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xabar holati',
                'verbose_name_plural': 'Xabar holatlari',
                'constraints': [models.UniqueConstraint(fields=('message', 'user'), name='unique_message_state_per_user')],
            },
        ),
    ]
