# Generated by Django 6.1.1 on 2026-09-21 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_attachments/', verbose_name='Fayl')),
                ('original_name', models.CharField(max_length=255, verbose_name='Fayl nomi')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Fayl hajmi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message', verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Biriktirilgan fayl',
                'verbose_name_plural': 'Biriktirilgan fayllar',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
